---
name: Global Workflows

on:
  push:
    branches:
      - master

jobs:
  replicate_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Replicating global workflow
        uses: derberg/global-workflows-support@v0.0.2
        with:
          commit_message: 'chore(ci): update global workflows'
          committer_email: webmaster@pixelmontogo.com
          committer_username: ptgbot
          files_to_ignore: global-workflows.yaml,branch-protection.yaml
          github_token: ${{ secrets.PAT }}
